# Generated by Django 5.1.4 on 2025-01-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_testgis'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
