# Generated by Django 5.1.4 on 2025-01-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_property_garbage_charges_property_water_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacetype',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
