# Generated by Django 4.2.17 on 2025-01-19 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_spacetype_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyfeature',
            name='propertytype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listing.propertytype'),
        ),
    ]
