# Generated by Django 4.2.17 on 2025-01-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_propertyfeature_propertytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='property',
            name='security_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='property',
            name='water_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
