# Generated by Django 4.2.17 on 2025-01-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_property_other_charges_property_security_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyfeature',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
