# Generated by Django 4.2.17 on 2025-02-15 10:40

from django.db import migrations, models
import listing.models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_alter_propertyfeature_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owners_contact',
            field=models.CharField(blank=True, default='', max_length=255, null=True, validators=[listing.models.check_phone]),
        ),
    ]
