# Generated by Django 4.2.17 on 2025-03-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_property_owners_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
