# Generated by Django 4.2.17 on 2025-03-09 07:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0013_alter_property_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('connectionfullname', models.TextField(unique=True)),
                ('contact', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits only.', regex='^\\d{10}')])),
                ('propertylink', models.SlugField(max_length=2000, null=True)),
                ('moved_in', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=18)),
                ('updated_at', models.DateField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.property')),
            ],
        ),
    ]
