# Generated by Django 5.1.4 on 2025-01-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentersuser',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
