# Generated by Django 4.2.17 on 2025-03-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_remove_rentersuser_max_otp_try_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentersuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
