# Generated by Django 5.1.4 on 2025-01-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rentersuser_otp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=2000, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rentersuser',
            name='max_otp_try',
        ),
        migrations.RemoveField(
            model_name='rentersuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='rentersuser',
            name='otp_expiry',
        ),
        migrations.RemoveField(
            model_name='rentersuser',
            name='otp_max_out',
        ),
        migrations.RemoveField(
            model_name='rentersuser',
            name='otp_secret',
        ),
    ]
