# Generated by Django 4.2.17 on 2025-03-06 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_rentersuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='contact',
            field=models.CharField(default='07', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='created_at',
            field=models.DateField(auto_created=True, default=datetime.datetime(2025, 3, 6, 12, 8, 39, 493962)),
        ),
        migrations.AddField(
            model_name='otp',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 12, 8, 39, 493900)),
        ),
        migrations.AddField(
            model_name='otp',
            name='salt',
            field=models.CharField(default='test', max_length=2000, unique=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
