# Generated by Django 4.2.17 on 2025-03-06 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otp_contact_otp_created_at_otp_expiration_otp_salt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateField(auto_created=True, default=datetime.datetime(2025, 3, 6, 13, 48, 48, 131595)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 13, 48, 48, 131538)),
        ),
    ]
