# Generated by Django 4.2.17 on 2025-03-06 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otp_created_at_alter_otp_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateField(auto_created=True, default=datetime.datetime(2025, 3, 6, 14, 11, 23, 706869)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 14, 11, 23, 706816)),
        ),
    ]
