# Generated by Django 4.2.17 on 2025-03-09 07:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_otp_salt_alter_otp_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('connectionfullname', models.TextField(unique=True)),
                ('contact', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits only.', regex='^\\d{10}')])),
                ('propertylink', models.SlugField(max_length=2000, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateField(auto_created=True, default=datetime.datetime(2025, 3, 9, 10, 42, 6, 759995)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 9, 10, 42, 6, 759939)),
        ),
    ]
