# Generated by Django 4.2.17 on 2025-03-09 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_connections_alter_otp_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connections',
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateField(auto_created=True, default=datetime.datetime(2025, 3, 9, 10, 59, 31, 74638)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 9, 10, 59, 31, 74602)),
        ),
    ]
